### ISSUE TITLE
Tried enabling S3 support via ACPI patch?

### ISSUE THREAD

**Issue by dmarkey** [tlvince/framework-laptop-13-amd-7640u#1]
Although would be completely unsupported, have you played with the idea of patching the ACPI tables to enable S3 suspend support?

**Comment by tlvince** [comment]
I've not tried this. As far as I know, S3 was dropped in Rembrandt, so haven't looked further. I did some testing in 98fa4e1cbb00da880a00e8484a3dd3dd611d5c5d - s2idle reaches S0i3.0 and drains ~4.7% battery in ~12 hours, which I'm satisfied with.

https://github.com/DavidS95/Smokeless_UMAF is an option if you want to dig into this 😄
